export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_PENDING = "FETCH_EVENTS_PENDING";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";
export const UPDATE_EVENT_STATE = "UPDATE_EVENT_STATE";
export const SELECT_EVENTS = "SELECT_EVENT";
