export const FETCH_EVENTS_PENDING = "FETCH_EVENTS_PENDING";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";
export const UPDATE_EVENT_STATE = "UPDATE_EVENT_STATE";
export const UPDATE_SELECTION_PRICE = "UPDATE_SELECTION_PRICE";
export const UPDATE_SELECTION_STATE = "UPDATE_SELECTION_STATE";
